### ISSUE TITLE
[Edit] Trinkets computing

### ISSUE THREAD

**Issue by keithgeeker** [Marsgames/GearHelper#108]
after this latest patch it is not showing the +scores when i point to an item..   ALSO yall need a WAY better scoring system for TRINKETS...............

**Comment by Marsgames** [comment]
Hey,

I just released an update that should fix issue with score (GearHelper in general). You can found it here if it’s not yet in CurseForge software : https://www.curseforge.com/wow/addons/gearhelper/files/3515330

Trinket, fingers, and weapons are particulary hard to to compute. We’ll work on it as soon as we have some spare time.


Thank you for your feedback.

**Comment by Marsgames** [comment]
Computation should be better with GearHelper 3.3.X

If the issue is due to stats weights, custom weights templates can be created
