### ISSUE TITLE
Latency when loading screen 

### ISSUE THREAD

**Issue by Marsgames** [Marsgames/GearHelper#12]
~~It seams to be caused by PoseDot. (GearHelper.lua, called in GH_Events --> BagUpdate + PlayerEnteringWorld).~~

~~Add script to each ContainerFrame(1->5):IsVisible() to call PoseDot only when the frame is visible and not at each loading screen ?~~

~~https://us.battle.net/forums/en/wow/topic/20753406958~~

NewWeightCalculation seams to add **11s** at login
GetStatsFromTemplate seams to add **13s** at login

**Comment by Mantisis** [comment]
@Marsgames is able to reproduce the issue
On my side i'm not able

**Comment by Mantisis** [comment]
event BAG_UPDATE is fired 200 times when /camp and 400 times on first load (or after a /quit)
It call poseDot which execute NewWeightCalculation for each object so for 100 objects it means 20K call for each loading screen
As NewWeightCalculation call GetItemInfo and it may take sometime 1 sec to get data from server, it add a lot of time at each loading screen
