### ISSUE TITLE
Hovering over Alchemist training options causes error 

### ISSUE THREAD

**Issue by MarshallBuhl** [Marsgames/GearHelper#123]
While visiting the Alchemy shop in Dalaran (Northrend), I get an error when attempting to learn a recipe from Linzy Blackbolt.  That is, if I hover over either a trainable or untrainable alchemy skill I get the following error:
============================================================ (my divider)
Message: Interface\AddOns\GearHelper\GearHelper.lua:481: table index is nil
Time: Sun Mar 13 16:42:42 2022
Count: 23
Stack: Interface\AddOns\GearHelper\GearHelper.lua:481: table index is nil
[string "@Interface\AddOns\GearHelper\GearHelper.lua"]:481: in function <Interface\AddOns\GearHelper\GearHelper.lua:375>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetTrainerService'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals: self = GameTooltip {
 0 = <userdata>
 SetText = <function> defined =[C]:-1
 SetPvpTalent = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 ARKTTD = <table> {
 }
 SetLootCurrency = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 FadeOut = <function> defined =[C]:-1
 SetQuestLogSpecialItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetSpellByID = <function> defined =[C]:-1
 NineSlice = <unnamed> {
 }
 SetCompanionPet = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetAction = <function> defined =[C]:-1
 SetCurrencyByID = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetArtifactPowerByID = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 ClearLines = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 Backdrop = GHGameTooltipBackdrop {
 }
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 hasMoney = 1
 SetQuestItem = <function> defined =[C]:-1
 numMoneyFrames = 1
 waitingForData = false
 SetToyByItemID = <function> defined =[C]:-1
 comparing = false
 SetInboxItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetTalent = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 SetRecipeRankInfo = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 textLeft2Font = "GameTooltipText"
 updateTooltipTimer = 0.103000
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetItemKey = <function> defined =[C]:-1
 needsReset = true
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetTradeTargetItem = <function> defined =[C]:-1
 SetQuestLogCurrency = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
}
name = nil
itemLink = nil
shouldBeCompared = false
err = "...erface\AddOns\GearHelper\Gear\GH_StatComputation.lua:32: ItemLink is not valid"
linesToAdd = <table> {
}
isItemEquipped = false
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"
tooltipProcessed = <table> {
}
ShouldDisplayNotEquippable = <function> defined @Interface\AddOns\GearHelper\GearHelper.lua:360
L = <table> {
 demande4esES2 = " que acabas de recibir "
 demande2 = " if he needs "
 DNR = "Do not
============================================================ (my divider)
I don't know if the unfinished line at the end is part of the problem or just an artifact of the error system in that there is a limit in the number of characters allowed.

I am a level 60 mage and my WotLK alchemy skill is 25.

**Comment by Marsgames** [comment]
Cannot reproduce. Seems to be fix with previous update
