### ISSUE TITLE
wrong result from IsEquippedItem

### ISSUE THREAD

**Issue by deathcore01** [Marsgames/GearHelper#13]
the wow api function IsEquippedItem give wrong result in many cases (i have equipped the legion weapon and the result from IsEquippedItem is false). this result in a wrong tooltip display, if i move the mouse pointer over the equiped weapon, the tooltip say "This item is worse than your" instead of "This item is equipped"

to repair this change in file "GearHelper.lua" the funtion "GearHelper:IsItemBetter), line 448 from

	if (IsEquippedItem(object)) then
		return {-60}
	end

to:

    local id = GetItemInfoInstant(object)
    if (id and IsEquippedItem(id)) or (IsEquippedItem(object)) then
        return {-60}
     end

**Comment by Marsgames** [comment]
Thank you for your message.
An update version should be release in about 3 days, this issue will be fix.

Thanks again for contributing.

**Comment by deathcore01** [comment]
no problem... (sorry for my bad english, can anyone speak german?)
a i must say, here are more problems... if i have a bag into my inventory (Frostweave Bag as a example) and i move the mouse cursor over it, gearhelper say "This  item is worse than your" - this is a completely wrong message, this item is not for equip... i think, here more problems with item info funtions... many it's a better way to check item with item id instead of item link, wow api has problems at the actual time... hope u can understand my english...

**Comment by Mantisis** [comment]
Hi deathcore,

Sorry for the delay, and the fact we can't help you directly in german :p but don't worry i've understood what you've said.
I'm refactoring stuff on GearHelper to improve reliability from some functions because as you've mentioned it WoW API lack reliability in many ways.
I'll take a look at it as soon as possible.
Thank for your feedback :)

**Comment by Mantisis** [comment]
@deathcore01 I've check the results and everything looks good on items i have tested
If you go into the GearHelper main options pane there is an option "Show non equippable items", if you disable this, GearHelper will stop to display "this item is worse than yours" on item that you can't equip.

Please reopen issue if your problem persist :)

Cheers
