### ISSUE TITLE
[FEATURE REQUEST] How to create a function to know when the player is equipped with one or more items? Lua

### ISSUE THREAD

**Issue by seninha26** [Marsgames/GearHelper#131]
I want to know how to identify when the player is using / equipping an item, because when he equips the 5 items, the npc will give him a buff, and when he removes a single item or more, he loses the buff.

I was looking on github but couldn't understand.
https://elunaluaengine.github.io/Item/IsEquipped.html
https://elunaluaengine.github.io/Global/RegisterItemEvent.html

For Lua/Eluna engine for WoW 3.3.5

**Comment by Marsgames** [comment]
You can use event "UNIT_INVENTORY_CHANGED" to be informed when a player equips or une quips an item.
Then you can run through character item slots to get which items are equipped or not, and be aware if the 5 required items are equipped

**Comment by seninha26** [comment]
And how do I do that? Can you help me? My script is like this. https://pastebin.com/N5BJSu5s
