### ISSUE TITLE
Since the pre-patch, the app (which I love!) has stopped working across all my characters.  If it's relevant, the app is colored green (the only one colored green) in my wow app page.  I have uninstalled and reinstalled repeatedly.  Any advice would be welcome.  Thank you!!

### ISSUE THREAD

**Issue by zmgl2** [Marsgames/GearHelper#135]
**Describe the bug**

**To Reproduce**
If this bug is due to *itemLink*, *hovering*, *quest reward*, or any other way where an item can be the cause, please provide us
- Your class
- Your level
- Your spec
- What item / quest is causing this issue

**Additional context**

**Comment by Marsgames** [comment]
Hey, 
Thank you for your message.

Many api changes occurred with the prematch 10.0.2, so we have some work to do on the add-on.
There was a complete reforge of the tooltip system, that we mainly use to compute items differences.

Be sure we're working on it, to release a new update as soon as possible

**Comment by zmgl2** [comment]
Thank you, and good luck!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
