### ISSUE TITLE
error [BUG] 

### ISSUE THREAD

**Issue by Imna1975** [Marsgames/GearHelper#143]
2x GearHelper/Localizations/enUS.lua:1: Cannot find a library instance of "AceLocale-3.0".
[string "=[C]"]: in function `error'
[string "@BugSack/Libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@GearHelper/Localizations/enUS.lua"]:1: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceLocale-3.0"."

2x GearHelper/Localizations/enUS.lua:1 (null)  this is the error for all languages 

the error third for all languages on

**Comment by Marsgames** [comment]
Hey, do you have AceLocale-3.0 into your GearHelper/Libs folder ?

**Comment by Imna1975** [comment]
yes I have
