### ISSUE TITLE
[BUG] Evoker - GH_Items.lua:133: bad argument #1 to 'foreach' (table expected, got nil)

### ISSUE THREAD

**Issue by Siodar** [Marsgames/GearHelper#147]
**Getting non stop LUA messages only on Evoker race**

**Logon a Evoker**
If this bug is due to *itemLink*, *hovering*, *quest reward*, or any other way where an item can be the cause, please provide us
- Your class
- Your level
- Your spec
- What item / quest is causing this issue

**Message: Interface/AddOns/GearHelper/Gear/GH_Items.lua:133: bad argument #1 to 'foreach' (table expected, got nil)
Time: Sun Jan 29 19:47:29 2023
Count: 9
Stack: Interface/AddOns/GearHelper/Gear/GH_Items.lua:133: bad argument #1 to 'foreach' (table expected, got nil)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `foreach'
[string "@Interface/AddOns/GearHelper/Gear/GH_Items.lua"]:133: in function `IsEquippableByMe'
[string "@Interface/AddOns/GearHelper/Hooks/GH_ItemTooltip.lua"]:32: in function <Interface/AddOns/GearHelper/Hooks/GH_ItemTooltip.lua:12>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
...
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/Durability.lua"]:52: in function `eventFunc'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:409: in function `AssignPanelToDataText'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:559: in function `UpdatePanelInfo'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:577: in function `LoadDataTexts'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:804: in function `?'
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Scrap/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...face/AddOns/Scrap/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = <function> defined =[C]:-1**
**Message: Interface/AddOns/GearHelper/Gear/GH_Template.lua:9: attempt to index field '?' (a nil value)
Time: Sun Jan 29 19:47:30 2023
Count: 1
Stack: Interface/AddOns/GearHelper/Gear/GH_Template.lua:9: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/GearHelper/Gear/GH_Template.lua"]:9: in function `GetStatFromActiveTemplate'
[string "@Interface/AddOns/GearHelper/Gear/GH_Items.lua"]:177: in function `GetScore'
[string "@Interface/AddOns/GearHelper/Gear/GH_ItemCompare.lua"]:28: in function `GetEquippedItemsScore'
[string "@Interface/AddOns/GearHelper/Gear/GH_ItemCompare.lua"]:53: in function `CompareWithEquipped'
[string "@Interface/AddOns/GearHelper/Gear/GH_ItemCompare.lua"]:8: in function `IsItemBetter'
[string "@Interface/AddOns/GearHelper/Inventory/GH_ShowUpgradeIcon.lua"]:8: in function `ShowUpgradeOnItemsIcons'
[string "@Interface/AddOns/GearHelper/Events/GH_Bag.lua"]:19: in function <Interface/AddOns/GearHelper/Events/GH_Bag.lua:13>
[string "=[C]"]: ?
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Scrap/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...face/AddOns/Scrap/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>**

**Comment by Marsgames** [comment]
This issue is due to Evoker not added to GH_Constants.ITEM_TYPES_EQUIPPABLE_BY_CLASS.

Easy fix
