### ISSUE TITLE
Items not equals are showed as equals

### ISSUE THREAD

**Issue by Marsgames** [Marsgames/GearHelper#15]
"Is this a bug or do I need to change some setting? they are obviously not equal items. One items is +80 points better."

<img width="857" alt="image" src="https://user-images.githubusercontent.com/9108765/52747937-4f8a7100-2fe5-11e9-8f67-22e7a0206bde.png">

**Comment by Mantisis** [comment]
#7 seems to be linked with this one, both need to be investigated
