### ISSUE TITLE
Crash when use invalid GH command for the first time

### ISSUE THREAD

**Issue by Mantisis** [Marsgames/GearHelper#27]
Stacktrace :

Message: AceLocale-3.0: GearHelper: Missing entry for 'helpConfig'
Time: Thu Feb 21 00:03:01 2019
Count: 1
Stack: AceLocale-3.0: GearHelper: Missing entry for 'helpConfig'
...rface\AddOns\GearHelper\Commands\GH_SlashMethods.lua:6: in function `SlashDisplayHelp'
Interface\AddOns\GearHelper\Commands\GH_Slash.lua:3: in function `help'
Interface\AddOns\GearHelper\Commands\GH_Slash.lua:85: in function `?'
...arHelper\Libs\Ace3\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4757: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4418: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4454: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: <none>

Repro : 
Launch game or reload
Type /gh foobar or any invalid command

**Comment by Marsgames** [comment]
Fix in GH 2.7
