### ISSUE TITLE
Error when click on Custom Weights radio

### ISSUE THREAD

**Issue by Marsgames** [Marsgames/GearHelper#5]
~When you click for the first time on a radio CW~

Message: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:878: attempt to index field 'rootframe' (a nil value)
Time: Fri Nov 30 10:50:01 2018
Count: 1
Stack: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:878: attempt to index field 'rootframe' (a nil value)
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:878: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:875>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...ddOns\GearHelper\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...bs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...bs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Locals: <none>

**Comment by Mantisis** [comment]
Not able to reproduce

**Comment by Mantisis** [comment]
Not linked to the fact that's the first time you click on it

**Comment by Mantisis** [comment]
Not reliably reproducible and the error come from inside Ace

**Comment by Marsgames** [comment]
Old issue, seems to be fixed
