### ISSUE TITLE
GearHelper.lua error

### ISSUE THREAD

**Issue by cptcl** [Marsgames/GearHelper#55]
So i get this in chat... Tryed deleting, reinstall.. nothing helps

[15:39:01] Interface\AddOns\GearHelper\GearHelper.lua:585: in function `BuildItemFromTooltip'
Interface\AddOns\GearHelper\GearHelper.lua:652: in function `GetItemByLink'
Interface\AddOns\GearHelper\GearHelper.lua:714: in function <Interface\AddOns\GearHelper\GearHelper.lua:664>
[C]: in function `pcall'
Interface\AddOns\GearHelper\GearHelper.lua:536: in function `IsItemBetter'
Interface\AddOns\GearHelper\GearHelper.lua:408: in function `poseDot'
Interface\AddOns\GearHelper\GH_Events.lua:122: in function <Interface\AddOns\GearHelper\GH_Events.lua:104>
[C]: ?
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by cptcl** [comment]
But only on one toon Oo

**Comment by Mantisis** [comment]
Thanks for reporting, will check that, get back yo you asap :)

**Comment by Mantisis** [comment]
It seems that you have an item with an invalid hyperlink in your inventory
Added a proper error while this is happening

**Comment by Mantisis** [comment]
Fixed in #56
