### ISSUE TITLE
LUA Error :(

### ISSUE THREAD

**Issue by NaomiErin** [Marsgames/GearHelper#58]
Been getting this pop up for awhile now

`Date: 2019-10-03 13:52:58
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GearHelper\GH_Events.lua line 325:
   attempt to compare number with nil
Debug:
   GearHelper\GH_Events.lua:325:
      GearHelper\GH_Events.lua:251
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:64: Fire()
   ...ddOns\GatherMate2\Libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...ddOns\GatherMate2\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None

`

**Comment by Marsgames** [comment]
Hey, thank you for your report.
This should be fix with the new version present on Curse.
