### ISSUE TITLE
GearHelper-1.7.5.lua:720: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by Marsgames** [Marsgames/GearHelper#6]
https://wow.curseforge.com/projects/gearhelper/issues/20

Message: Interface\AddOns\GearHelper\GearHelper-1.7.5.lua:720: attempt to perform arithmetic on a nil value
Time: Mon Sep 24 15:44:01 2018
Count: 129
Stack: Interface\AddOns\GearHelper\GearHelper-1.7.5.lua:720: attempt to perform arithmetic on a nil value
Locals: <none>

----------------------------------------------------

9051x GearHelper\GearHelper-1.7.5.lua:720: attempt to perform arithmetic on a nil value
GearHelper\GearHelper-1.7.5.lua:720: in function 'ApplyTemplateToDelta'
GearHelper\GearHelper-1.7.5.lua:1042: in function 'NewWeightCalculation'
GearHelper\GearHelper-1.7.5.lua:784: in function 'IsItemBetter'
GearHelper\GearHelper-1.7.5.lua:659: in function 'poseDot'
GearHelper\GH_Events.lua:136: in function <GearHelper\GH_Events.lua:118>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function '?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:90: in function 'Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Mantisis** [comment]
Cannot reproduce issue & v1.7.5 not supported anymore, reopen if needed
