### ISSUE TITLE
spams

### ISSUE THREAD

**Issue by Trixz2018** [Marsgames/GearHelper#61]
everytime i get a new item this spams in my chat 

[13:38] Interface\AddOns\GearHelper\GearHelper.lua:585: in function `BuildItemFromTooltip'
Interface\AddOns\GearHelper\GearHelper.lua:652: in function `GetItemByLink'
Interface\AddOns\GearHelper\GearHelper.lua:714: in function <Interface\AddOns\GearHelper\GearHelper.lua:664>
[C]: in function `pcall'
Interface\AddOns\GearHelper\GearHelper.lua:536: in function `IsItemBetter'
Interface\AddOns\GearHelper\GearHelper.lua:408: in function `poseDot'
Interface\AddOns\GearHelper\GH_Events.lua:122: in function <Interface\AddOns\GearHelper\GH_Events.lua:104>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandl

**Comment by Marsgames** [comment]
Fix with release 2.7.1

**Comment by Trixz2018** [comment]
still getting it

**Comment by Marsgames** [comment]
Can you give me the entire message ?
