### ISSUE TITLE
Attempt to perform arithmetic on a nil value - Error

### ISSUE THREAD

**Issue by CeloSG** [Marsgames/GearHelper#62]
Hello Marsgames first of all thank you for the great plugin unfortunately he is currently generating 2 LUA errors :/.

I have added the error message as Hastbin link.

https://hastebin.com/risorifilu.makefile

Thank you already 👍

**Comment by Marsgames** [comment]
@CeloSG Hey, thank you for your comment.
Are you using a custom template for your stats weight ?

**Comment by CeloSG** [comment]
No, I use Noxxic's stats weight. [Default]

**Comment by CeloSG** [comment]
If i run the Script command i dont get any response.

**Comment by Marsgames** [comment]
This is strange. I will push the new version, it should remove this issue, but it's sure that everything will works as it should

**Comment by CeloSG** [comment]
Super thank you very much now it goes!

OFFTOPIC: Maybe you can also add the new localization german :D

**Comment by Marsgames** [comment]
Wow, I didn't see it. Curse doesn't send me notification when a new translation is added.
I update it in a second.
(btw, I just added 5 translation, if you have the time to update them too 😃)

**Comment by CeloSG** [comment]
I'm sorry I was ingame. I translated it :D

**Comment by Marsgames** [comment]
Thank you, I'll add the translations tomorrow
