### ISSUE TITLE
WeightCalculation wand + offhand VS staff

### ISSUE THREAD

**Issue by Marsgames** [Marsgames/GearHelper#7]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9108765/49330628-6d713980-f591-11e8-9f4a-99bd3705b615.png">

Issue in WeightCalculation wand + tome vs staff

**Comment by Marsgames** [comment]
Un bâton est toujours mieux qu'une baguette + tome

**Comment by Mantisis** [comment]
@Marsgames please check if the bug is still present

**Comment by Marsgames** [comment]
@Mantisis still here
