### ISSUE TITLE
Lua Error when hovering over gear in backpack

### ISSUE THREAD

**Issue by the777ahmad** [Marsgames/GearHelper#72]
Message: Interface\AddOns\GearHelper\GearHelper.lua:962: Interface\AddOns\GearHelper\GearHelper.lua:597: ItemLink is not valid
Time: Wed Jan  8 02:24:36 2020
Count: 25
Stack: Interface\AddOns\GearHelper\GearHelper.lua:962: Interface\AddOns\GearHelper\GearHelper.lua:597: ItemLink is not valid
[C]: in function `error'
Interface\AddOns\GearHelper\GearHelper.lua:962: in function <Interface\AddOns\GearHelper\GearHelper.lua:930>
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1402: in function `ContainerFrameItemButton_OnEnter'
...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:378: in function `ShowTooltip'
...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:211: in function <...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:204>

Locals: (*temporary) = "Interface\AddOns\GearHelper\GearHelper.lua:597: ItemLink is not valid"

**Comment by jonnyzap** [comment]
I get the same error

**Comment by Marsgames** [comment]
This one shouldn't exist anymore
