### ISSUE TITLE
memory ?

### ISSUE THREAD

**Issue by Imna1975** [Marsgames/GearHelper#80]
high memory consumption in the game how can you change that

**Comment by Imna1975** [comment]
![WoWScrnShot_031020_194759 (2)](https://user-images.githubusercontent.com/45740014/76650590-3d219480-6563-11ea-8b7f-cbcd6e0806c4.jpg)

**Comment by Marsgames** [comment]
This should be due to our own items cache.
Maybe we will remove items that haven't been seen in a while to avoid to keep so much items (especially during level up)

**Comment by Imna1975** [comment]
Yes that would be nice

**Comment by Imna1975** [comment]
ram utilization is now around 60 mb, that's not nice anymore

**Comment by Marsgames** [comment]
Try /gh resetcache

**Comment by Imna1975** [comment]
thanks a lot that helped

**Comment by Marsgames** [comment]
Fix with commit 34cf937
We not remote items not seen since 35 days
