### ISSUE TITLE
issue #89 wasn't fixed

### ISSUE THREAD

**Issue by vaendryl** [Marsgames/GearHelper#94]
I don't quite understand why it seems I'm the only one who has this problem but even with the latest version of the addon and even clearing the cache files in the WTF folder I keep getting the same errors described in issue #89 - regardless of class or spec. 

as far as i can tell the instruction `return tostring(GearHelper.db.global.templates[(currentSpec)]["NOX"][stat])` fails consistently because the local variable currentSpec holds a string but the table expects an integer, causing it to return 'nil' instead of the proper value. changing the line above to `local currentSpec = tonumber(tostring(GetSpecializationInfo(GetSpecialization())))` fixes the problem for me, regardless of how silly it looks. 

I have injected this change in 3 places into the code to fix both the options menu and tooltips errors. I *think* it works for me now.

**Comment by Marsgames** [comment]
Hey, thank you for your feedback.
Indeed, I think when I changed my scrapping script, I accidentally replace spec string by spec number.

I suspect some accounts still have spec as strings, so it works for most people.

I'll add this fix in the next release.

**Comment by vaendryl** [comment]
thanks, I appreciate the fix. 
I hope this change doesn't break it for those people for whom it still works...

**Comment by Marsgames** [comment]
Thanks to you, it should work for everyone now ;)
