### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Imna1975** [Marsgames/GearHelper#96]
1x GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : nil
[string "=[C]"]: in function `error'
[string "@GearHelper\Gear\GH_TooltipHelper.lua"]:28: in function `BuildItemFromTooltip'
[string "@GearHelper\GH_Cache.lua"]:23: in function `GetItemByLink'
[string "@GearHelper\GH_Events.lua"]:320: in function <GearHelper\GH_Events.lua:304>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by NaomiErin** [comment]
It would seem this error is ongoing and ignored :(

**Comment by Mantisis** [comment]
Hi @NaomiErin (and @Imna1975)

I will take a look a this one, sorry for the late handling of the issue :)

**Comment by NaomiErin** [comment]
> Hi @NaomiErin (and @Imna1975)
> 
> I will take a look a this one, sorry for the late handling of the issue :)

Why thank you good sir. This is very good news as I use this a lot x
