### ISSUE TITLE
Errors when hovering over items in backpack

### ISSUE THREAD

**Issue by knightfire120** [Marsgames/GearHelper#99]
Interface\AddOns\GearHelper\GearHelper.lua:405: ...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1
Time: Sun Mar  7 10:47:01 2021
Count: 10
Stack: Interface\AddOns\GearHelper\GearHelper.lua:405: ...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\GearHelper\GearHelper.lua"]:405: in function <Interface\AddOns\GearHelper\GearHelper.lua:369>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\MobInfo2\MI2_Events.lua"]:358: in function <Interface\AddOns\MobInfo2\MI2_Events.lua:355>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceHook-3.0\AceHook-3.0.lua"]:95: in function <Interface\AddOns\Ace3\AceHook-3.0\AceHook-3.0.lua:87>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1324: in function `ContainerFrameItemButton_OnUpdate'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1371: in function `ContainerFrameItemButton_OnEnter'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua"]:369: in function `ShowTooltip'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua"]:340: in function `UpdateTooltip'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua"]:180: in function <...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:179>

Locals: (*temporary) = "...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1"

**Comment by NaomiErin** [comment]
Did you ever figure this one out because it's happening to me and the creator of this addon never seemed to have answered you?

**Comment by Marsgames** [comment]
Hey, can you tell us what kind of items cause this issue ? Do you have any examples ?

**Comment by NaomiErin** [comment]
> Hey, can you tell us what kind of items cause this issue ? Do you have any examples ?

So far, as far as I can tell it has been **shields** (**Wintersail Bulwark of the Peerless** in this case) from the **BFA expansion** but I can not confirm if this is the only item in question.

**Comment by NaomiErin** [comment]
I vaguely remember that there was an LUA edit that prevented this error from showing altogether by disabling a certain function. If I recall, it didn't interfere with the general operation of the addon but did stop the Lua errors from happening. Unfortunately I have Googled the poo out of this error and the results are far from helpful lol
